# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
          - name: dind
            alwaysPullImage: 'false'
            envVars:
              - envVar:
                  key: DOCKER_TLS_CERTDIR
                  value: /certs
              - envVar:
                  key: "DOCKER_IPTABLES_LEGACY"
                  value: "1"
            image: docker:dind
            args: "--default-address-pool base=192.168.96.0/20,size=24"  # overwrite docker subnet in case of overlapping
            livenessProbe:
              failureThreshold: '0'
              initialDelaySeconds: '0'
              periodSeconds: '0'
              successThreshold: '0'
              timeoutSeconds: '0'
            privileged: 'true'
            ttyEnabled: 'true'
            workingDir: /home/jenkins/agent
