// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//    https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
//
//
// Jenkins declaration of how to build and test the current codebase.
//  Jenkins infrastructure related settings should be kept in
//    https://github.com/apache/cassandra-builds/blob/trunk/jenkins-dsl/cassandra_job_dsl_seed.groovy
//
// Validate/lint this file using the following command
// `curl -X POST  -F "jenkinsfile=<.jenkins/Jenkinsfile" https://ci-cassandra.apache.org/pipeline-model-converter/validate`

// METHOD TOO LARGE ISSUE: https://issues.jenkins.io/browse/JENKINS-37984
// Run in Jenkins Script Console: 
// org.jenkinsci.plugins.pipeline.modeldefinition.parser.RuntimeASTTransformer.SCRIPT_SPLITTING_TRANSFORMATION=true
// org.jenkinsci.plugins.pipeline.modeldefinition.parser.RuntimeASTTransformer.SCRIPT_SPLITTING_ALLOW_LOCAL_VARIABLES=true

def jdksSupported = ["11", "17"] // Updating JDKs? Don't forget to update matrix axis (stages 'jar' and 'Tests'), they can't use variables :(
def archsSupported = ["amd64", "arm64"] // Updating Archs? Don't forget to update matrix axis (stages 'jar' and 'Tests'), they can't use variables :(
def jdkDefault = 11
def stageFailed = false
def splits = 5
def stepsMap = [
  jar: [type: 'build', script: 'build-jars.sh', toCopy: null],
  artifacts: [type: 'build', script: 'build-artifacts.sh', toCopy: 'apache-cassandra-*.tar.gz,apache-cassandra-*.jar,apache-cassandra-*.pom'],
  lint: [type: 'build', script: 'check-code.sh', toCopy: null],
  debian: [type: 'build', script: 'build-debian.sh', toCopy: 'cassandra_*,cassandra-tools_*'],
  redhat: [type: 'build', script: 'build-redhat.sh rpm', toCopy: '*.rpm'],
  'cqlsh-test': [type: 'test', test: 'cqlsh-test'],
  'fqltool-test': [type: 'test', test: 'fqltool-test'],
  'test-cdc': [type: 'test', test: 'test-cdc', splits: splits],
  'test': [type: 'test', test: 'test', splits: splits],
  'test-trie': [type: 'test', test: 'test-trie', splits: splits],
]

pipeline {
  agent none
  options {
    skipDefaultCheckout()
    // retry(3) // Do we need it?
  }
  parameters {
    string(name: 'repository', defaultValue: 'https://github.com/HadesArchitect/cassandra', description: 'Cassandra Repository')
    string(name: 'branch', defaultValue: '*/aleks-cassius', description: 'Branch')
    choice(name: 'architecture', choices: archsSupported + "all", description: 'Pick architecture. The ARM64 is disabled by default at the moment.')
    choice(name: 'jdk', choices: jdksSupported + "all", description: 'Pick JDK versions.')
    booleanParam(name: 'stage_artifacts', defaultValue: false, description: 'Disable to exlude stage') // return default to true
    booleanParam(name: 'stage_lint', defaultValue: false) // return default to true
    booleanParam(name: 'stage_debian', defaultValue: false) // return default to true
    booleanParam(name: 'stage_redhat', defaultValue: false) // return default to true
    booleanParam(name: 'stage_fqltool-test', defaultValue: false) // return default to true
    booleanParam(name: 'stage_cqlsh-test', defaultValue: false) // return default to true
    booleanParam(name: 'stage_test-cdc', defaultValue: false) // return default to true
    booleanParam(name: 'stage_test', defaultValue: false) // return default to true
    booleanParam(name: 'stage_test-trie', defaultValue: false) // return default to true
  }
  environment {
    javaVersionsSupported = jdksSupported.join(',')
    javaVersionDefault = "${jdkDefault}"
  }
  stages {
    stage('jar') {
      matrix {
        axes {
          axis { 
            name 'arch'
            values 'amd64', 'arm64'
          }
          axis { 
            name 'jdk'
            values '11', '17'
          }
        }
        when {
          allOf {
            expression { isArchEnabled(env.arch) }
            expression { isJdkEnabled(env.jdk) }
          }
        }
        stages {
          stage('jar') {
            steps {
              _build('jar', stepsMap['jar'])
            }
          }
        }
      }
    }
    stage('Tests') {
      matrix {
        axes {
            axis { 
              name 'arch'
              values 'amd64', 'arm64'
            }
            axis { 
              name 'jdk'
              values '11', '17'
            }
            axis { 
              name 'step'
              values 'artifacts', 'lint', 'debian', 'redhat', 'cqlsh-test', 'fqltool-test', 'test-cdc', 'test', 'test-trie'
            }
            axis { 
              name 'python'
              values '3.7', '3.8', '3.11'
            }
            axis { 
              name 'cython'
              values 'yes', 'no'
            }
            axis { 
              name 'split'
              values 1, 2, 3, 4, 5
            }
        }
        excludes {
          exclude { // Allow only python 3.7 for all steps (except cqlsh-test)
            axis {
              name 'step'
              notValues 'cqlsh-test'
            }
            axis {
              name 'python'
              notValues '3.7'
            }
          }
          exclude { // Allow only amd64 for cqlsh-test
            axis {
              name 'step'
              values 'cqlsh-test'
            }
            axis {
              name 'arch'
              notValues 'amd64'
            }
          }
          exclude { // Disable cython for all but cqlsh-test
            axis {
              name 'step'
              notValues 'cqlsh-test'
            }
            axis {
              name 'cython'
              values 'yes'
            }
          }
          exclude { // Disable splits for all but proper stages
            axis {
              name 'step'
              notValues 'test-cdc', 'test', 'test-trie'
            }
            axis {
              name 'split'
              notValues 1
            }
          }
        }
        when {
          allOf {
            expression { isArchEnabled(env.arch) }
            expression { isJdkEnabled(env.jdk) }
            expression { isStageEnabled(env.step) }
          }
        }
        stages {
          stage('test') { // Looks weird but we can't set custom stage name here, only in substage
            steps {
              _matrixSteps()
            }
          }
        }
      }
    }
  }
}

def _matrixSteps() {
  return script {
    stage(getStepName(step, arch, jdk, python, cython, split, stepsMap[step])) {
      if ('build' == stepsMap[step].type) {
        _build(step, stepsMap[step])
      } else {
        _test(stepsMap[step])
      }
    }
  }
}
    //         _test("test-compression", [current: 2, all: 10])
    //         _test("stress-test")
    //         testJob("test-burn", 10)
    //         testJob("long-test", 8)
    //         testJob("test-oa", 8)
    //         testJob("test-system-keyspace-directory", 8)
    //         _dtest("jvm-dtest", 8)
    //         testJob("jvm-dtest-upgrade", 8)
    // stage('Summary') {
    //   steps {
    //     // generateUnifiedTestReport()
    //     // FIXME – post always
    //     // sendNotifications()
    //     script {
    //       if (stageFailed) {
    //         currentBuild.result='FAILURE'
    //         error("Build failed due to failed stages")
    //       }
    //     }
    //   }
    // }
  // }
//   post {
//     always {
//       cleanWs()
//     }
//   }
//   }
// }

///////////////////////////
//// scripting support ////
///////////////////////////

def getStepName(step, arch, jdk, python, cython, split, command) {
  arch = "amd64" == arch ? "" : " ${arch}"
  python = "cqlsh-test" != step ? "" : " python${python}"
  cython = "no" == cython ? "" : " cython"
  split = command.containsKey('splits') && command.splits > 1 ? " ${split}/${command.splits}" : ""

  return "${step}${arch} jdk${jdk}${python}${cython}${split}"
}

/**
 * Return the default JDK defined by build.xml
 **/
def javaVersionDefault() {
  sh (returnStdout: true, script: 'grep \'property\\s*name=\"java.default\"\' build.xml | sed -ne \'s/.*value=\"\\([^\"]*\\)\".*/\\1/p\'').trim()
}

/**
 * Return the supported JDKs defined by build.xml
 **/
def javaVersionsSupported() {
  sh (returnStdout: true, script: 'grep \'property\\s*name=\"java.supported\"\' build.xml | sed -ne \'s/.*value=\"\\([^\"]*\\)\".*/\\1/p\'').trim()
}

/**
 * Is this a post-commit build (or a pre-commit build)
 **/
def isPostCommit() {
  // any build of a branch found on github.com/apache/cassandra is considered a post-commit (post-merge) CI run
  return "${GIT_URL}".contains("apache/cassandra")
}

/**
 * Are we running on ci-cassandra.apache.org ?
 **/
def isCanonical() {
  return "${JENKINS_URL}".contains("ci-cassandra.apache.org")
}

def isStageEnabled(stage) {
  return params."stage_${stage}" || "jar" == stage
}

def isArchEnabled(arch) {
  return params.architecture == arch || "all" == params.architecture
}

def isJdkEnabled(jdk) {
  return params.jdk == jdk || "all" == params.jdk
}

/**
 * Renders build script into pipeline steps
 **/
def _build(step, command) {
    def build_script = command.script
    def toCopy = command.toCopy
    node(getNodeArch(arch)) {
        ws("workspace/${JOB_NAME}/${BUILD_NUMBER}/${step}/${arch}/jdk-${jdk}") {
            cleanWs(disableDeferredWipeout: true)
            fetchSource(step, arch, jdk)

            build_script = ".build/docker/${build_script}"
            def logfile = "${JOB_NAME}_${BUILD_NUMBER}_${step}_jdk${jdk}_${arch}.log"

            catchError(buildResult: null, message: 'Build task failed', stageResult: 'FAILURE') {
                // sh script:"#!/usr/bin/bash; set -o pipefail; build_dir='${WORKSPACE}/build' ${build_script} ${jdk} 2>&1 | tee ${logfile}"
                sh label: 'RUNNING BUILD TASK...', script: "#!/usr/bin/bash \nset -o pipefail; build_dir='${WORKSPACE}/build' ${build_script} ${jdk} 2>&1 | tee ${logfile}"
                if ("jar" == step) { // only stash the project built files. all dependency libraries are restored from the local maven repo using `ant resolver-dist-lib`
                    stash name: "${arch}_${jdk}", useDefaultExcludes: false //, includes: '**/*.jar' //, includes: "*.jar,classes/**,test/classes/**,tools/**"
                }
                copyToNightlies("${toCopy}", "${STAGE_NAME}/jdk${jdk}/${arch}/")
            }
            sh "xz -f *.log"
            archiveArtifacts artifacts: "**/*.log.xz", fingerprint: true
            copyToNightlies("**/*.log.xz", "${step}/jdk${jdk}/${arch}/")
            cleanAgent(build_script)
        }
    }
}

def _test(command) { //, arch, jdk, python, cython, split) {
  def test_type = command.test
  def split = env.split
  def splits = command.splits
  def python = env.python
  def cython = env.cython
  node(getNodeArch(arch)) {
    ws("workspace/${JOB_NAME}/${BUILD_NUMBER}/${test_type}/${arch}/jdk-${jdk}/python-${python}") {
      cleanWs(disableDeferredWipeout: true)
      fetchSource(test_type, arch, jdk)
      def logfile = "${JOB_NAME}_${BUILD_NUMBER}_${test_type}_jdk${jdk}_python_${python}_${cython}_${arch}.log"

// sh "mkdir -p build"
// def build_dir = sh( returnStdout: true, script:"mktemp -d ${WORKSPACE}/build/build_docker_run.XXXXXXXXXX" ).trim()
// def build_dir_rel = build_dir - "${WORKSPACE}/"

// dir("${build_dir}") {
  // fetchSource(test_type, arch, jdk)
// }
      catchError(buildResult: null, message: 'Tests failed', stageResult: 'FAILURE') {
          sh label: "RUNNING TESTS...", script: "#!/usr/bin/bash \nset -o pipefail; python_version='${python}' cython='${cython}' build_dir='${WORKSPACE}/build' .build/docker/run-tests.sh ${test_type} '${split}/${splits}' ${jdk} 2>&1 | tee ${logfile}"
          dir("build") {
            // junit testResults: "test/output/nosetests.xml", allowEmptyResults: true
            // junit testResults: "test/output/cqlshlib.xml", allowEmptyResults: true
            //sh "ls -la test/output/"
            junit testResults: "test/output/**/TEST*.xml", allowEmptyResults: true
            sh "xz -f test/output/**/TEST*.xml || true ; xz -f test/output/cqlshlib.xml test/output/nosetests.xml || true"
            // junit testResults: "test/output/**/TEST*.xml,test/output/cqlshlib.xml,test/output/nosetests.xml", testDataPublishers: [[$class: 'StabilityTestDataPublisher']]
            // junit testResults: "build/test/output/**/TEST*.xml,build/test/output/cqlshlib.xml,build/test/output/nosetests.xml"//, testDataPublishers: [[$class: 'StabilityTestDataPublisher']]
            // sh "xz -f build/test/output/**/TEST*.xml || true ; xz -f build/test/output/cqlshlib.xml build/test/output/nosetests.xml || true"
          }
      }
      sh "xz -f *.log"
      archiveArtifacts artifacts: "*.log.xz,build/**/*.log.xz,build/test/logs/**,build/test/output/**/TEST*.xml.xz,build/test/output/cqlshlib.xml.xz,build/test/output/nosetests.xml.xz", fingerprint: true
      // archiveArtifacts artifacts: "build/**/*.log.xz,build/test/logs/**,build/test/output/**/TEST*.xml.xz,build/test/output/cqlshlib.xml.xz,build/test/output/nosetests.xml.xz", fingerprint: true
      copyToNightlies("*.log.xz,build/test/logs/**", "${test_type}/${arch}/jdk${jdk}/python${python}/cython_${cython}/" + "split_${split}_${splits}".replace("/", "_"))
      
      cleanAgent(".build/docker/run-tests.sh")
    }
  }
}

def fetchSource(stage, arch, jdk) {
    if ("jar" == stage) {
        checkout changelog: false, scm: scmGit(branches: [[name: params.branch]], extensions: [cloneOption(depth: 1, noTags: true, reference: '', shallow: true)], userRemoteConfigs: [[url: params.repository]])
    } else {
        unstash name: "${arch}_${jdk}"
    }
}

/**
 * Saves JUnit results, fails if no reports are found
 * Copies (single-file unified) junit results and logfiles to nightlies
 * Cleans the agent (docker prune) afterwards
 * Stops the pipeline on any failure
 **/
// def testJob(test_type, splits=1) {
//   def jdks = STAGE_NAME.contains("dtest-upgrade") || "simulator-dtest".equals(STAGE_NAME) ? ["${javaVersionDefault}"] : "${javaVersionsSupported}".split(/,/, -1)
// }

/**
 * Backward compatibility to support ci-cassandra.a.o Renders node architecture by real architecture name
 **/
def getNodeArch(arch) {
  switch(arch) {
    case "amd64":
      return "cassandra"
    case "arm64":
      return "cassandra-arm64"
    default:
      error("Unsupported architecture '${arch}'")
  }
}

/**
 * Executes `.build/test-docker.sh ${testDockerImage} ${test_type} ${split}` for the stated arch, jdk, python, cython, and split.
 **/
def _testAxis(test_script, test_type, arch, jdk, python, cython, split) {
  echo "Spawning ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python${python} cython=${cython}"
  node(_getNodeArch(arch)) {
    branchName: "${STAGE_NAME} ${test_script} ${test_type} ${split} ${jdk} ${NODE_NAME}"
    echo "Starting ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python${python} cython=${cython} on ${NODE_NAME}"
    checkout scm
    sh "mkdir -p build"
    def build_dir = sh( returnStdout: true, script:"mktemp -d ${WORKSPACE}/build/build_docker_run.XXXXXXXXXX" ).trim()
    def build_dir_rel = build_dir - "${WORKSPACE}/"

    def cassandra_dtest_dir = "${build_dir}/cassandra-dtest"
    if (STAGE_NAME.startsWith("dtest")) {
        def dtestRepo = "https://github.com/apache/cassandra-dtest"
        def dtestBranch =  "trunk"
        sh "until git clone --quiet --depth 1 -b ${dtestBranch} ${dtestRepo} \"${cassandra_dtest_dir}\" ; do echo \"git cloning cassandra-dtest failed… trying again… \" ; done"
    }

    def statusCode = 0, attempt = 1
    retry(2) {
      if (attempt > 1) { sleep(60 * attempt) }
      def logfile = "${JOB_NAME}_${BUILD_NUMBER}_${test_type}_jdk${jdk}_python_${python}_${cython}_${arch}_attempt_${attempt}.log"
      try {
        dir("${build_dir}") {
          unstash name: "${arch}_${jdk}"
        }
        echo "Executing ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk} 2>&1 | tee ${build_dir}/${logfile}` on ${NODE_NAME} with jdk=${jdk} python=${python} cython=${cython}"
        statusCode = sh returnStatus:true, script:"python_version=\"${python}\" cython=\"${cython}\" build_dir=\"${build_dir}\" cassandra_dtest_dir=\"${cassandra_dtest_dir}\" ${test_script} ${test_type} ${split} ${jdk} 2>&1 | tee ${build_dir}/${logfile}"
      } finally {
        dir("${build_dir_rel}") {
            if (0 == statusCode) {
                junit testResults: "test/output/**/TEST*.xml,test/output/cqlshlib.xml,test/output/nosetests.xml", testDataPublishers: [[$class: 'StabilityTestDataPublisher']]
                sh "xz -f test/output/**/TEST*.xml || true ; xz -f test/output/cqlshlib.xml test/output/nosetests.xml || true"
            }
            archiveArtifacts artifacts: "**/*_attempt_*.log.xz,test/logs/**,test/output/**/TEST*.xml.xz,test/output/cqlshlib.xml.xz,test/output/nosetests.xml.xz", fingerprint: true
            copyToNightlies("*_attempt_*.log.xz,test/logs/**", "${test_type}/${arch}/jdk${jdk}/python${python}/cython_${cython}/" + "split_${split}".replace("/", "_"))
        }
        sh "rm -rf \"${build_dir}\""
        cleanAgent(test_script)
        if (0 != statusCode) {
          currentBuild.result = 'FAILURE'
          error("FAILED ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python=${python} cython=${cython} on ${NODE_NAME}")
        } else {
          echo "Completed ${STAGE_NAME} `${test_script} ${test_type} ${split} ${jdk}` with arch=${arch} jdk=${jdk} python=${python} cython=${cython} on ${NODE_NAME}"
        }
      }
    }

    if (currentBuild.result != 'SUCCESS') unstable("${STAGE_NAME} failures (arch=${arch} jdk=${jdk} python=${python} cython=${cython} on ${NODE_NAME})")
    if (currentBuild.result == 'ABORTED' && currentBuild.result != 'FAILURE') currentBuild.result='ABORTED'
    if (currentBuild.result == 'FAILURE') currentBuild.result='FAILURE'
  }
}

def copyToNightlies(sourceFiles, remoteDirectory='') {
    if (!isCanonical() || "" == sourceFiles) {
        return;
    }

    def remotePath = remoteDirectory.startsWith("cassandra/") ? "${remoteDirectory}" : "cassandra/${JOB_NAME}/${BUILD_NUMBER}/${remoteDirectory}"
    def attempt = 1
    retry(9) {
        if (attempt > 1) { sleep(60 * attempt) }
        sshPublisher(
        continueOnError: true, failOnError: false,
        publishers: [
            sshPublisherDesc(
            configName: "Nightlies",
            transfers: [ sshTransfer( sourceFiles: sourceFiles, remoteDirectory: remotePath) ]
            )
        ])
    }
    echo "archived to https://nightlies.apache.org/${remotePath}"
}

def cleanAgent(job_name) {
  if (isCanonical()) {
    def maxJobHours = 12
    echo "Cleaning project, processes, docker for '${job_name}' on ${NODE_NAME}…" ;
    sh """
        git clean -qxdff -e build/test/jmh-result.json || true;
        if pgrep -xa docker || pgrep -af "build/docker" || pgrep -af "cassandra-builds/build-scripts" ; then docker system prune --all --force --filter "until=${maxJobHours}h" || true ; else  docker system prune --force --volumes || true ;  fi;
      """
  }
}

//  CASSANDRA-18130
def saveAgentReport() {
  if (isCanonical()) {
    //
    // echo "Updating disk usage report…";
    // sh """
    //     ( echo "----" ;
    //     echo \$(date) ;
    //     echo "${JOB_NAME} ${BUILD_NUMBER} ${STAGE_NAME}" ;
    //     du -xm / 2>/dev/null | sort -rn | head -n 30 ;
    //     df -h ) | tee -a \$(date +"%Y%m%d%H%M")-disk-usage-stats.txt
    //   """
    //   copyToNightlies("*-disk-usage-stats.txt", "cassandra/agents/${NODE_NAME}/disk-usage/")
    //   sh 'rm *-disk-usage-stats.txt'
  }
}

/////////////////////////////////////////
////// scripting support for summary ////
/////////////////////////////////////////

def generateUnifiedTestReport() {
  assert "Summary".equals(STAGE_NAME)
  node(_('amd64')) {
    checkout scm
    sh "mkdir -p build"
    copyArtifacts filter: 'test/output/**/*.xml.xz', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER), target: "build/"
    sh 'xz -d build/test/output/**/*.xml.xz || true ; xz -d test/output/cqlshlib.xml test/output/nosetests.xml || true'
    sh ".build/docker/_docker_run.sh bullseye-build.docker generate-test-report.sh"
    dir('build/') {
      sh "xz -f TESTS-TestSuites.xml"
      archiveArtifacts artifacts: "TESTS-TestSuites.xml.xz,test/html/**/*", fingerprint: true
      copyToNightlies('TESTS-TestSuites.xml.xz')
    }
  }
}

def sendNotifications() {
  if (isPostCommit() && isCanonical()) {
    // the following is expected only to work on ci-cassandra.apache.org
    try {
      script {
        changes = formatChangeLogChanges(currentBuild.changeSets)
        echo "changes: ${changes}"
      }
      slackSend channel: '#cassandra-builds', message: ":apache: <${BUILD_URL}|${currentBuild.fullDisplayName}> completed: ${currentBuild.result}. <https://github.com/apache/cassandra/commit/${GIT_COMMIT}|${GIT_COMMIT}>\n${changes}"
      emailext to: 'builds@cassandra.apache.org', subject: "Build complete: ${currentBuild.fullDisplayName} [${currentBuild.result}] ${GIT_COMMIT}", presendScript: 'msg.removeHeader("In-Reply-To"); msg.removeHeader("References")', body: emailContent()
    } catch (Exception ex) {
      echo 'failed to send notifications  ' + ex.toString()
    }
  }
}

def formatChangeLogChanges(changeLogSets) {
  def result = ''
  for (int i = 0; i < changeLogSets.size(); i++) {
    def entries = changeLogSets[i].items
    for (int j = 0; j < entries.length; j++) {
      def entry = entries[j]
      result = result + "${entry.commitId} by ${entry.author} on ${new Date(entry.timestamp)}: ${entry.msg}\n"
    }
  }
  return result
}

def emailContent() {
  return '''
  -------------------------------------------------------------------------------
  Build ${ENV,var="JOB_NAME"} #${BUILD_NUMBER} ${BUILD_STATUS}
  URL: ${BUILD_URL}
  -------------------------------------------------------------------------------
  Changes:
  ${CHANGES}
  -------------------------------------------------------------------------------
  Failed Tests:
  ${FAILED_TESTS,maxTests=500,showMessage=false,showStack=false}
  -------------------------------------------------------------------------------
  For complete test report and logs see https://nightlies.apache.org/cassandra/${JOB_NAME}/${BUILD_NUMBER}/
  '''
}
