= Audit Logging

Audit Logging is a new feature in Apache Cassandra 4.0 (https://issues.apache.org/jira/browse/CASSANDRA-12151[CASSANDRA-12151]).
All database activity is logged to a directory in the local filesystem and the audit log files are rolled periodically. 
All database operations are monitored and recorded. 
Audit logs are stored in local directory files instead of the database itself as it provides several benefits, some of which are:

* No additional database capacity is needed to store audit logs
* No query tool is required while storing the audit logs in the database would require a query tool
* Latency of database operations is not affected; no performance impact
* It is easier to implement file based logging than database based logging

== What does Audit Logging Log?

Audit logging logs:

* All authentication which includes successful and failed login attempts
* All database command requests to CQL. Both failed and successful CQL is logged

More specifically an audit log entry could be one of two types:

* CQL Audit Log Entry Type or
* Common Audit Log Entry Type

Each of these types comprises of several database operations. The CQL
Audit Log Entry Type could be one of the following; the category of the
CQL audit log entry type is listed in parentheses.

* SELECT(QUERY),
* UPDATE(DML),
* DELETE(DML),
* TRUNCATE(DDL),
* CREATE_KEYSPACE(DDL),
* ALTER_KEYSPACE(DDL),
* DROP_KEYSPACE(DDL),
* CREATE_TABLE(DDL),
* DROP_TABLE(DDL),
* PREPARE_STATEMENT(PREPARE),
* DROP_TRIGGER(DDL),
* LIST_USERS(DCL),
* CREATE_INDEX(DDL),
. DROP_INDEX(DDL),
. GRANT(DCL),
. REVOKE(DCL),
. CREATE_TYPE(DDL),
. DROP_AGGREGATE(DDL),
. ALTER_VIEW(DDL),
. CREATE_VIEW(DDL),
. DROP_ROLE(DCL),
. CREATE_FUNCTION(DDL),
. ALTER_TABLE(DDL),
. BATCH(DML),
. CREATE_AGGREGATE(DDL),
. DROP_VIEW(DDL),
. DROP_TYPE(DDL),
. DROP_FUNCTION(DDL),
. ALTER_ROLE(DCL),
. CREATE_TRIGGER(DDL),
. LIST_ROLES(DCL),
. LIST_PERMISSIONS(DCL),
. ALTER_TYPE(DDL),
. CREATE_ROLE(DCL),
. USE_KEYSPACE (OTHER).

The Common Audit Log Entry Type could be one of the following; the
category of the Common audit log entry type is listed in parentheses.

[arabic]
. REQUEST_FAILURE(ERROR),
. LOGIN_ERROR(AUTH),
. UNAUTHORIZED_ATTEMPT(AUTH),
. LOGIN_SUCCESS (AUTH).

== What Audit Logging does not Log?

Audit logging does not log:

[arabic]
. Configuration changes made in `cassandra.yaml`
. Nodetool Commands

== Audit Logging is Flexible and Configurable

Audit logging is flexible and configurable in `cassandra.yaml` as
follows:

* Keyspaces and tables to be monitored and audited may be specified.
* Users to be included/excluded may be specified. By default all users
are audit logged.
* Categories of operations to audit or exclude may be specified.
* The frequency at which to roll the log files may be specified. Default
frequency is hourly.

== Configuring Audit Logging

The ``cassandra.yaml`` file can be used to configure and enable audit logging.
Configuration and enablement may be the same or different on each node, depending on the ``cassandra.yaml`` file settings.
Audit logs are generated on each enabled node, so logs on each node will have that node's queries.
All options for audit logging can be set in the ``cassandra.yaml`` file under the `audit_logging_options:`.

The file includes the following options that can be uncommented for use:

[source, yaml]
----
# Audit logging - Logs every incoming CQL command request, authentication to a node. See the docs
# on audit_logging for full details about the various configuration options.
audit_logging_options:
    enabled: false
    logger:
      - class_name: BinAuditLogger
    # audit_logs_dir:
    # included_keyspaces:
    # excluded_keyspaces: system, system_schema, system_virtual_schema
    # included_categories:
    # excluded_categories:
    # included_users:
    # excluded_users:
    # roll_cycle: HOURLY
    # block: true
    # max_queue_weight: 268435456 # 256 MiB
    # max_log_size: 17179869184 # 16 GiB
    ## archive command is "/path/to/script.sh %path" where %path is replaced with the file being rolled:
    # archive_command:
    # max_archive_retries: 10
----

=== enabled

Audit logging is enabled by setting the `enabled` option to `true` in
the `audit_logging_options` setting. For example, ``enabled: true``.

=== logger

The type of audit logger is set with the `logger` option. 
Supported values are: `BinAuditLogger` (default), `FileAuditLogger` and `NoOpAuditLogger`.
`BinAuditLogger` logs events to a file in binary format. 
`FileAuditLogger` uses the standard logging mechanism, `slf4j` to log events to the `audit/audit.log` file. It is a synchronous, file-based audit logger.
`NoOpAuditLogger` is a no-op implementation of the audit logger that shoudl be specified when audit logging is disabled.

For example:

[source, yaml]
----
logger: 
  - class_name: FileAuditLogger
----


=== audit_logs_dir

To write audit logs, an existing directory must be set in ``audit_log_dir``.

The directory must have appropriate permissions set to allow reading, writing, and executing.
Logging will recursively delete the directory contents as needed.
Do not place links in this directory to other sections of the filesystem.
For example, ``audit_log_dir: /cassandra/audit/logs/hourly``.

The audit log directory can also be configured using the system property `cassandra.logdir.audit`, which by default is set to `cassandra.logdir + /audit/`.

=== included_keyspaces and excluded_keyspaces

Set the keyspaces to include with the `included_keyspaces` option and
the keyspaces to exclude with the `excluded_keyspaces` option. 
By default, `system`, `system_schema` and `system_virtual_schema` are excluded, and all other keyspaces are included.

For example:
[source, yaml]
----
included_keyspaces: test, demo
excluded_keyspaces: system, system_schema, system_virtual_schema
----

=== included_categories and excluded_categories

The categories of database operations to include are specified with the `included_categories` option as a comma-separated list. 
The categories of database operations to exclude are specified with `excluded_categories` option as a comma-separated list. 
The supported categories for audit log are: `AUTH`, `DCL`, `DDL`, `DML`, `ERROR`, `OTHER`, `PREPARE`, and `QUERY`.
By default all supported categories are included, and no category is excluded. 

[source, yaml]
----
included_categories: AUTH, ERROR, DCL
excluded_categories: DDL, DML, QUERY, PREPARE
----

=== included_users and excluded_users

Users to audit log are set with the `included_users` and `excluded_users` options. 
The `included_users` option specifies a comma-separated list of users to include explicitly.
The `excluded_users` option specifies a comma-separated list of users to exclude explicitly.
By default all users are included, and no users are excluded. 

[source, yaml]
----
included_users: 
excluded_users: john, mary
----

=== roll_cycle

The ``roll_cycle`` defines the frequency with which the audit log segments are rolled.
Supported values are ``HOURLY`` (default), ``MINUTELY``, and ``DAILY``.
For example: ``roll_cycle: DAILY``

=== block

The ``block`` option specifies whether audit logging should block writing or drop log records if the audit logging falls behind. Supported boolean values are ``true`` (default) or ``false``.
For example: ``block: false`` to drop records

=== max_queue_weight

The ``max_queue_weight`` option sets the maximum weight of in-memory queue for records waiting to be written to the file before blocking or dropping.  The option must be set to a positive value. The default value is 268435456, or 256 MiB.
For example, to change the default: ``max_queue_weight: 134217728 # 128 MiB``

=== max_log_size

The ``max_log_size`` option sets the maximum size of the rolled files to retain on disk before deleting the oldest file.  The option must be set to a positive value. The default is 17179869184, or 16 GiB.
For example, to change the default: ``max_log_size: 34359738368 # 32 GiB``

=== archive_command

The ``archive_command`` option sets the user-defined archive script to execute on rolled log files.
For example: ``archive_command: /usr/local/bin/archiveit.sh %path # %path is the file being rolled``

=== max_archive_retries

The ``max_archive_retries`` option sets the max number of retries of failed archive commands. The default is 10.
For example: ``max_archive_retries: 10``


An audit log file could get rolled for other reasons as well such as a
log file reaches the configured size threshold.

Audit logging can also be configured using ``nodetool` when enabling the feature, and will override any values set in the `cassandra.yaml` file, as discussed in the next section.


== Enabling Audit Logging with ``nodetool``
 
Audit logging is enabled on a per-node basis using the ``nodetool enableauditlog`` command. At a minimum, the path to the logging directory must be defined, if ``audit_log_dir`` is not set in the `cassandra.yaml` file.

The syntax of the ``nodetool enableauditlog`` command has all the same options that can be set in the ``cassandra.yaml`` file.
In addition, ``nodetool`` has options to set which host and port to run the command on, and username and password if the command requires authentication.

The `nodetool  enableauditlog` command may be used to enable audit logs
and it overrides the settings in `cassandra.yaml`. The
`nodetool enableauditlog` command syntax is as follows.

....
nodetool [(-h <host> | --host <host>)] [(-p <port> | --port <port>)]
        [(-pp | --print-port)] [(-pw <password> | --password <password>)]
        [(-pwf <passwordFilePath> | --password-file <passwordFilePath>)]
        [(-u <username> | --username <username>)] enableauditlog
        [--excluded-categories <excluded_categories>]
        [--excluded-keyspaces <excluded_keyspaces>]
        [--excluded-users <excluded_users>]
        [--included-categories <included_categories>]
        [--included-keyspaces <included_keyspaces>]
        [--included-users <included_users>] [--logger <logger>]
....

OPTIONS::
  --excluded-categories <excluded_categories>;;
    Comma separated list of Audit Log Categories to be excluded for
    audit log. If not set the value from cassandra.yaml will be used
  --excluded-keyspaces <excluded_keyspaces>;;
    Comma separated list of keyspaces to be excluded for audit log. If
    not set the value from cassandra.yaml will be used
  --excluded-users <excluded_users>;;
    Comma separated list of users to be excluded for audit log. If not
    set the value from cassandra.yaml will be used
  -h <host>, --host <host>;;
    Node hostname or ip address
  --included-categories <included_categories>;;
    Comma separated list of Audit Log Categories to be included for
    audit log. If not set the value from cassandra.yaml will be used
  --included-keyspaces <included_keyspaces>;;
    Comma separated list of keyspaces to be included for audit log. If
    not set the value from cassandra.yaml will be used
  --included-users <included_users>;;
    Comma separated list of users to be included for audit log. If not
    set the value from cassandra.yaml will be used
  --logger <logger>;;
    Logger name to be used for AuditLogging. Default BinAuditLogger. If
    not set the value from cassandra.yaml will be used
  -p <port>, --port <port>;;
    Remote jmx agent port number
  -pp, --print-port;;
    Operate in 4.0 mode with hosts disambiguated by port number
  -pw <password>, --password <password>;;
    Remote jmx agent password
  -pwf <passwordFilePath>, --password-file <passwordFilePath>;;
    Path to the JMX password file
  -u <username>, --username <username>;;
    Remote jmx agent username

The `nodetool disableauditlog` command disables audit log. The command
syntax is as follows.

....
nodetool [(-h <host> | --host <host>)] [(-p <port> | --port <port>)]
        [(-pp | --print-port)] [(-pw <password> | --password <password>)]
        [(-pwf <passwordFilePath> | --password-file <passwordFilePath>)]
        [(-u <username> | --username <username>)] disableauditlog
....

OPTIONS::
  -h <host>, --host <host>;;
    Node hostname or ip address
  -p <port>, --port <port>;;
    Remote jmx agent port number
  -pp, --print-port;;
    Operate in 4.0 mode with hosts disambiguated by port number
  -pw <password>, --password <password>;;
    Remote jmx agent password
  -pwf <passwordFilePath>, --password-file <passwordFilePath>;;
    Path to the JMX password file
  -u <username>, --username <username>;;
    Remote jmx agent username

== Viewing the Audit Logs

An audit log event comprises of a keyspace that is being audited, the
operation that is being logged, the scope and the user. An audit log
entry comprises of the following attributes concatenated with a "|".

....
type (AuditLogEntryType): Type of request
source (InetAddressAndPort): Source IP Address from which request originated
user (String): User name
timestamp (long ): Timestamp of the request
batch (UUID): Batch of request
keyspace (String): Keyspace on which request is made
scope (String): Scope of request such as Table/Function/Aggregate name
operation (String): Database operation such as CQL command
options (QueryOptions): CQL Query options
state (QueryState): State related to a given query
....

Some of these attributes may not be applicable to a given request and
not all of these options must be set.

== An Audit Logging Demo

To demonstrate audit logging enable and configure audit logs with
following settings.

....
audit_logging_options:
   enabled: true
   logger: BinAuditLogger
   audit_logs_dir: "/cassandra/audit/logs/hourly"
   # included_keyspaces:
   # excluded_keyspaces: system, system_schema, system_virtual_schema
   # included_categories:
   # excluded_categories:
   # included_users:
   # excluded_users:
   roll_cycle: HOURLY
   # block: true
   # max_queue_weight: 268435456 # 256 MiB
   # max_log_size: 17179869184 # 16 GiB
   ## archive command is "/path/to/script.sh %path" where %path is replaced with the file being rolled:
   # archive_command:
   # max_archive_retries: 10
....

Create the audit log directory `/cassandra/audit/logs/hourly` and set
its permissions as discussed earlier. Run some CQL commands such as
create a keyspace, create a table and query a table. Any supported CQL
commands may be run as discussed in section *What does Audit Logging
Log?*. Change directory (with `cd` command) to the audit logs directory.

....
cd /cassandra/audit/logs/hourly
....

List the files/directories and some `.cq4` files should get listed.
These are the audit logs files.

....
[ec2-user@ip-10-0-2-238 hourly]$ ls -l
total 28
-rw-rw-r--. 1 ec2-user ec2-user 83886080 Aug  2 03:01 20190802-02.cq4
-rw-rw-r--. 1 ec2-user ec2-user 83886080 Aug  2 03:01 20190802-03.cq4
-rw-rw-r--. 1 ec2-user ec2-user    65536 Aug  2 03:01 directory-listing.cq4t
....

The `auditlogviewer` tool is used to dump audit logs. Run the
`auditlogviewer` tool. Audit log files directory path is a required
argument. The output should be similar to the following output.

....
[ec2-user@ip-10-0-2-238 hourly]$ auditlogviewer /cassandra/audit/logs/hourly
WARN  03:12:11,124 Using Pauser.sleepy() as not enough processors, have 2, needs 8+
Type: AuditLog
LogMessage:
user:anonymous|host:10.0.2.238:7000|source:/127.0.0.1|port:46264|timestamp:1564711427328|type :USE_KEYSPACE|category:OTHER|ks:auditlogkeyspace|operation:USE AuditLogKeyspace;
Type: AuditLog
LogMessage:
user:anonymous|host:10.0.2.238:7000|source:/127.0.0.1|port:46264|timestamp:1564711427329|type :USE_KEYSPACE|category:OTHER|ks:auditlogkeyspace|operation:USE "auditlogkeyspace"
Type: AuditLog
LogMessage:
user:anonymous|host:10.0.2.238:7000|source:/127.0.0.1|port:46264|timestamp:1564711446279|type :SELECT|category:QUERY|ks:auditlogkeyspace|scope:t|operation:SELECT * FROM t;
Type: AuditLog
LogMessage:
user:anonymous|host:10.0.2.238:7000|source:/127.0.0.1|port:46264|timestamp:1564713878834|type :DROP_TABLE|category:DDL|ks:auditlogkeyspace|scope:t|operation:DROP TABLE IF EXISTS
AuditLogKeyspace.t;
Type: AuditLog
LogMessage:
user:anonymous|host:10.0.2.238:7000|source:/3.91.56.164|port:42382|timestamp:1564714618360|ty
pe:REQUEST_FAILURE|category:ERROR|operation:CREATE KEYSPACE AuditLogKeyspace
WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};; Cannot add
existing keyspace "auditlogkeyspace"
Type: AuditLog
LogMessage:
user:anonymous|host:10.0.2.238:7000|source:/127.0.0.1|port:46264|timestamp:1564714690968|type :DROP_KEYSPACE|category:DDL|ks:auditlogkeyspace|operation:DROP KEYSPACE AuditLogKeyspace;
Type: AuditLog
LogMessage:
user:anonymous|host:10.0.2.238:7000|source:/3.91.56.164|port:42406|timestamp:1564714708329|ty pe:CREATE_KEYSPACE|category:DDL|ks:auditlogkeyspace|operation:CREATE KEYSPACE
AuditLogKeyspace
WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1};
Type: AuditLog
LogMessage:
user:anonymous|host:10.0.2.238:7000|source:/127.0.0.1|port:46264|timestamp:1564714870678|type :USE_KEYSPACE|category:OTHER|ks:auditlogkeyspace|operation:USE auditlogkeyspace;
[ec2-user@ip-10-0-2-238 hourly]$
....

The `auditlogviewer` tool usage syntax is as follows.

....
./auditlogviewer
Audit log files directory path is a required argument.
usage: auditlogviewer <path1> [<path2>...<pathN>] [options]
--
View the audit log contents in human readable format
--
Options are:
-f,--follow       Upon reaching the end of the log continue indefinitely
                  waiting for more records
-h,--help         display this help message
-r,--roll_cycle   How often to roll the log file was rolled. May be
                  necessary for Chronicle to correctly parse file names. (MINUTELY, HOURLY,
                  DAILY). Default HOURLY.
....

== Diagnostic events for user audit logging

Any native transport enabled client is able to subscribe to diagnostic
events that are raised around authentication and CQL operations. These
events can then be consumed and used by external tools to implement a
Cassandra user auditing solution.
