# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Template yaml (helm upgrade will not work directly on it) for
# https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
# This yaml is primarily used by .build/run-ci
#
# It exists as a template as the includes yaml files can be manually
# inserted where anchor references are
#

# fixed deployments will want to set the controller.ingress.hostName
persistence:
  enabled: true
  size: "500Gi"
  # aws needs gp2, gke can be left commented
  #storageClass: "gp2"
controller:
  # To get URL run `kubectl describe svc cassius-jenkins | grep 'LoadBalancer Ingress'`
  serviceType: LoadBalancer
  servicePort: 80
  targetPort: 8080
  ingress:
    enabled: true
    # uncomment and set if you have a "ci-cassandra" dns entry for the jenkins controller
    #hostName: ci-cassandra.<your-domain>
  customJenkinsLabels:
    - controller
  resources:
    requests:
      cpu: 6
      memory: 16G
    limits:
      cpu: 8
      memory: 20G
  javaOpts: -server -XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=40 -Xms8G -Xmx8G
  installPlugins:
    - job-dsl
    - configuration-as-code
    - kubernetes
    - git
    - workflow-job
    - workflow-cps
    - junit
    - workflow-aggregator
    - pipeline-graph-view
    - ws-cleanup
    - pipeline-build-step
    - pipeline-rest-api
    - test-stability
    - copyartifact
    - jmh-report
  nodeSelector:
    cassandra.jenkins.controller: "true"
  scriptApproval:
    - "staticMethod java.lang.System setProperty java.lang.String java.lang.String"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods combinations java.util.Collection"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getAt java.lang.Object java.lang.String"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods inspect java.lang.Object"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods max java.util.Collection"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods putAt java.util.List java.util.List java.lang.Object"
    - "method org.jenkinsci.plugins.workflow.steps.FlowInterruptedException getCauses"
  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to Apache Cassandra
      # we still need separate jobs because Jenkinsfile can differ (and are read before parameters are applied).
      #  if a dev branch alters the Jenkinsfile, it will not be picked up by the job – you need to edit the job configuration
      #  see the CAUTION warning in .jenkins/Jenkinsfile
      # TODO: add new version each release branching
      test-job: |
        jobs:
          - script: &pipeline-job-template |
              def createPipelineJob(name, gitBranch) {
                pipelineJob(name) {
                  definition {
                    cpsScm {
                      scm {
                        git {
                          remote {
                            url('https://github.com/apache/cassandra')
                          }
                          branch(gitBranch)
                          scriptPath('.jenkins/Jenkinsfile')
                        }
                      }
                      lightweight()
                    }
                  }
                }
              }
              createPipelineJob('cassandra', 'trunk')
              createPipelineJob('cassandra-5.0', 'cassandra-5.0')
    globalDefaultFlowDurabilityLevel:
      durabilityHint: "PERFORMANCE_OPTIMIZED"
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "admin"
          name: "Jenkins Admin"
          password: "${chart-admin-password}"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: true
    googlePodMonitor:
        enabled: true
agent:
  disableDefaultAgent: true
  maxRequestsPerHostStr: "3200"
  containerCap: 300
  nodeSelector:
    cassandra.jenkins.agent: "true"
  waitForPodSec: "180"
  podTemplates:
    agent-dind-small: |
      - name: agent-dind-small
        <<: *pod-template-base
        label: agent-dind cassandra-small cassandra-amd64-small
        nodeSelector: 'cassandra.jenkins.agent.small=true'
        instanceCap: 50
        instanceCapStr: "50"
        containers:
          <<: *jnlp-container-base
            resourceRequestCpu: 1
            resourceLimitCpu: 2
            resourceRequestMemory: 1G
            resourceLimitMemory: 1G
          <<: *dind-container-base
            resourceRequestCpu: 2
            resourceLimitCpu: 4
            resourceRequestMemory: 1G
            resourceLimitMemory: 2400M
        volumes: *volumes-base
    agent-dind-large-spot: |
      - name: agent-dind-small-spot
        <<: *pod-template-base
        label: agent-dind cassandra-small-spot cassandra-amd64-small-spot
        nodeSelector: 'cassandra.jenkins.agent.small.spot=true'
        instanceCap: 200
        instanceCapStr: "200"
        containers:
          <<: *jnlp-container-base
          <<: *dind-container-base
            resourceRequestCpu: 6
            resourceLimitCpu: 7
            resourceRequestMemory: 16G
            resourceLimitMemory: 30G
        volumes: *volumes-base
    agent-dind-medium: |
      - name: agent-dind-medium
        <<: *pod-template-base
        label: agent-dind cassandra-medium cassandra-amd64-medium
        nodeSelector: 'cassandra.jenkins.agent.medium=true'
        instanceCap: 100
        instanceCapStr: "100"
        containers:
          <<: *jnlp-container-base
          <<: *dind-container-base
            resourceRequestCpu: 2
            resourceLimitCpu: 4
            resourceRequestMemory: 3400M
            resourceLimitMemory: 5G
        volumes: *volumes-base
    agent-dind-medium-spot: |
      - name: agent-dind-medium-spot
        <<: *pod-template-base
        label: agent-dind cassandra-medium-spot cassandra-amd64-medium-spot
        nodeSelector: 'cassandra.jenkins.agent.medium.spot=true'
        instanceCap: 200
        instanceCapStr: "200"
        containers:
          <<: *jnlp-container-base
          <<: *dind-container-base
            resourceRequestCpu: 6
            resourceLimitCpu: 7
            resourceRequestMemory: 16G
            resourceLimitMemory: 30G
        volumes: *volumes-base
    agent-dind-large: |
      - name: agent-dind-large
        <<: *pod-template-base
        label: agent-dind cassandra-large cassandra-amd64-large
        nodeSelector: 'cassandra.jenkins.agent.large=true'
        instanceCap: 200
        instanceCapStr: "200"
        containers:
          <<: *jnlp-container-base
          <<: *dind-container-base
            resourceRequestCpu: 6
            resourceLimitCpu: 7
            resourceRequestMemory: 16G
            resourceLimitMemory: 30G
        volumes: *volumes-base
    agent-dind-large-spot: |
      - name: agent-dind-large-spot
        <<: *pod-template-base
        label: agent-dind cassandra-large-spot cassandra-amd64-large-spot
        nodeSelector: 'cassandra.jenkins.agent.large.spot=true'
        instanceCap: 200
        instanceCapStr: "200"
        containers:
          <<: *jnlp-container-base
          <<: *dind-container-base
            resourceRequestCpu: 6
            resourceLimitCpu: 7
            resourceRequestMemory: 16G
            resourceLimitMemory: 30G
        volumes: *volumes-base
